<a href="https://colab.research.google.com/github/Preet1990/Numpy-Project/blob/main/Numpy_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [35]:
data_file='KAG_Conversion_Data.csv'


In [34]:

data_str = np.genfromtxt(data_file, delimiter=",",skip_header=1,dtype=str)
data_float = np.genfromtxt(data_file, delimiter=",",skip_header=1,dtype=float)

print("\nData: \n\n", data_str)


Data: 

 [['708746' '916' '103916' ... '1.429999948' '2' '1']
 ['708749' '916' '103917' ... '1.820000023' '2' '0']
 ['708771' '916' '103920' ... '0' '1' '0']
 ...
 ['1314412' '1178' '179979' ... '40.28999949' '2' '0']
 ['1314414' '1178' '179981' ... '198.7100005' '8' '2']
 ['1314415' '1178' '179982' ... '165.6099987' '5' '2']]


In [36]:
data_float

array([[7.08746000e+05, 9.16000000e+02, 1.03916000e+05, ...,
        1.42999995e+00, 2.00000000e+00, 1.00000000e+00],
       [7.08749000e+05, 9.16000000e+02, 1.03917000e+05, ...,
        1.82000002e+00, 2.00000000e+00, 0.00000000e+00],
       [7.08771000e+05, 9.16000000e+02, 1.03920000e+05, ...,
        0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       ...,
       [1.31441200e+06, 1.17800000e+03, 1.79979000e+05, ...,
        4.02899995e+01, 2.00000000e+00, 0.00000000e+00],
       [1.31441400e+06, 1.17800000e+03, 1.79981000e+05, ...,
        1.98710001e+02, 8.00000000e+00, 2.00000000e+00],
       [1.31441500e+06, 1.17800000e+03, 1.79982000e+05, ...,
        1.65609999e+02, 5.00000000e+00, 2.00000000e+00]])

In [ ]:
xyz_id = data_str[:,1]
np.unique(xyz_id,return_counts=True)

(array(['1178', '916', '936'], dtype='<U11'), array([625,  54, 464]))

In [ ]:
unique_id,count= np.unique(xyz_id,return_counts=True)
print(unique_id)
print(count)

['1178' '916' '936']
[625  54 464]


In [ ]:
age_group= data_str[:,3]
np.unique(age_group)

array(['30-34', '35-39', '40-44', '45-49'], dtype='<U11')

In [53]:
ads_amount= data_float[:,8]
print(ads_amount)
print('-------------')
avg = ads_amount.mean()
print(avg)
print('-------------')
max = ads_amount.max()
print(max)
print('-------------')
min = ads_amount.min()
print(min)


[  1.42999995   1.82000002   0.         ...  40.28999949 198.7100005
 165.6099987 ]
-------------
51.36065613141295
-------------
639.9499981
-------------
0.0


In [41]:
click = data_float[:,7]
max_clicks = click.max()
max_clicks

421.0

In [44]:
id = data_float[:,0]
id[click==421]


array([1121814.])

In [45]:
Appro_conv = data_float[:,10]
Appro_conv[click==max_clicks]

array([13.])

In [47]:
max_approval = Appro_conv.max()
max_approval

21.0

In [48]:
data_float[Appro_conv==max_approval]


array([[1.12110400e+06, 1.17800000e+03, 1.44533000e+05,            nan,
                   nan, 1.60000000e+01, 2.08066600e+06, 2.02000000e+02,
        3.60150001e+02, 4.00000000e+01, 2.10000000e+01]])